aliases = {
    "alch" : "Alchemist",
    "aa" : "Ancient Apparition",
    "am" : "Anti-Mage",
#    "" : "Axe",
#    "" : "Bane",
    "bat" : "Batrider",
    "beast" : "Beastmaster",
    "bs" : "Bloodseeker",
    "bh" : "Bounty Hunter",
    "brew" : "Brewmaster",
    "brood" : "Broodmother",
    "ck" : "Chaos Knight",
#    "" : "Chen",
    "" : "Clinkz",
    "cent" : "Centaur Warrunner",
    "clock" : "Clockwerk",
    "cm" : "Crystal Maiden",
    "ds" : "Dark Seer",
    "daz" : "Dazzle",
    "dp" : "Death Prophet",
    "krob" : "Death Prophet",
    "thrall" : "Disruptor",
    "doom" : "Doom Bringer",
    "db" : "Doom Bringer",
    "dk" : "Dragon Knight",
    "drow" : "Drow Ranger",
    "es" : "Earthshaker",
    "chant" : "Enchantress",
#    "" : "Enigma",
    "void" : "Faceless Void",
    "gyro" : "Gyrocopter",
    "husk" : "Huskar",
#    "" : "Invoker",
    "thd" : "Jakiro",
    "jugg" : "Juggernaut",
    "kotl" : "Keeper of the Light",
    "kun" : "Kunkka",
    "lesh" : "Leshrac",
#    "" : "Lich",
    "naix" : "Lifestealer",
#    "" : "Lina",
#    "" : "Lion",
    "lone" : "Lone Druid",
    "ld" : "Lone Druid",
#    "" : "Luna",
    "lycan" : "Lycanthrope",
    "mag" : "Magnus",
#    "" : "Meepo",
    "" : "Mirana",
    "morph" : "Morphling",
    "naga" : "Naga Siren",
    "furion" : "Nature's Prophet",
    "np" : "Nature's Prophet",
    "necro" : "Necrolyte",
    "ns" : "Night Stalker",
    "na" : "Nyx Assassin",
    "nyx" : "Nyx Assassin",
    "ogre" : "Ogre Magi",
    "omni" : "Omniknight",
    "od" : "Outworld Destroyer",
    "pa" : "Phantom Assassin",
    "pl" : "Phantom Lancer",
#    "" : "Puck",
#    "" : "Pudge",
    "pug" : "Pugna",
    "qop" : "Queen of Pain",
#    "" : "Razor",
#   "" : "Riki",
    "rub" : "Rubick",
    "sand" : "Sand King",
    "sd" : "Shadow Demon",
    "sf" : "Shadow Fiend",
    "shsh" : "Shadow Shaman",
    "rhasta" : "Shadow Shaman",
    "sil" : "Silencer",
    "leoric" : "Skeleton King",
    "skel" : "Skeleton King",
    "slar" : "Slardar",
#    "" : "Sniper",
    "spec" : "Spectre",
    "sb" : "Spirit Breaker",
    "storm" : "Storm Spirit",
#    "" : "Sven",
    "ta" : "Templar Assassin",
    "tide" : "Tidehunter",
#    "" : "Tinker",
#    "" : "Tiny",
    "tree" : "Treant Protector",
    "tp" : "Treant Protector",
#    "" : "Undying",
#    "" : "Ursa",
    "vs" : "Vengeful Spirit",
    "veno" : "Venomancer",
#    "" : "Viper",
    "vis" : "Visage",
    "lock" : "Warlock",
#    "" : "Weaver",
    "wr" : "Windrunner",
#    "" : "Wisp",
    "wd" : "Witch Doctor",
#    "" : "Zeus",   
}
