pickbans = {
    "Dark Seer" : 437,
    "Rubick" : 426,
    "Leshrac" : 382,
    "Chen" : 374,
    "Naga Siren" : 366,
    "Tidehunter" : 365,
    "Templar Assassin" : 312,
    "Invoker" : 306,
    "Nature's Prophet" : 291,
    "Enigma" : 282,
    "Venomancer" : 280,
    "Chaos Knight" : 252,
    "Lycanthrope" : 245,
    "Broodmother" : 227,
    "Lone Druid" : 227,
    "Enchantress" : 223,
    "Bounty Hunter" : 217,
    "Queen of Pain" : 213,
    "Morphling" : 196,
    "Windrunner" : 196,
    "Brewmaster" : 195,
    "Batrider" : 192,
    "Anti-Mage" : 177,
    "Jakiro" : 166,
    "Shadow Shaman" : 158,
    "Wisp" : 144,
    "Sand King" : 132,
    "Tinker" : 124,
    "Shadow Demon" : 109,
    "Undying" : 109,
    "Keeper of the Light" : 107,
    "Disruptor" : 106,
    "Beastmaster" : 105,
    "Tiny" : 86,
    "Night Stalker" : 76,
    "Dragon Knight" : 61,
    "Shadow Fiend" : 57,
    "Storm Spirit" : 55,
    "Juggernaut" : 54,
    "Crystal Maiden" : 50,
    "Pudge" : 48,
    "Lina" : 45,
    "Ancient Apparition" : 43,
    "Sven" : 40,
    "Clinkz" : 38,
    "Lifestealer" : 38,
    "Faceless Void" : 36,
    "Earthshaker" : 33,
    "Puck" : 32,
    "Luna" : 31,
    "Vengeful Spirit" : 31,
    "Lich" : 28,
    "Bane" : 23,
    "Slardar" : 22,
    "Mirana" : 15,
    "Nyx Assassin" : 14,
    "Pugna" : 14,
    "Dazzle" : 13,
    "Phantom Lancer" : 13,
    "Magnataur" : 12,
    "Omniknight" : 12,
    "Alchemist" : 11,
    "Riki" : 11,
    "Death Prophet" : 10,
    "Doom Bringer" : 10,
    "Outworld Destroyer" : 10,
    "Kunkka" : 9,
    "Weaver" : 9,
    "Axe" : 8,
    "Lion" : 8,
    "Phantom Assassin" : 8,
    "Warlock" : 7,
    "Visage" : 6,
    "Clockwerk" : 5,
    "Treant Protector" : 5,
    "Drow Ranger" : 4,
    "Necrolyte" : 4,
    "Spiritbreaker" : 4,
    "Witch Doctor" : 4,
    "Razor" : 3,
    "Sniper" : 3,
    "Ursa" : 3,
    "Gyrocopter" : 2,
    "No Hero" : 2,
    "Viper" : 2,
    "Geomancer" : 1,
    "Huskar" : 1,
    "Ogre Magi" : 1,
    "Silencer" : 1,
    "Tauren Chieftain" : 1,
    "Zeus" : 1,
    }

