ranged_heroes = [ 
    "Ancient Apparition",
    "Bane",
    "Batrider",
    "Chen",
    "Clinkz",
    "Crystal Maiden",
    "Dazzle",
    "Death Prophet",
    "Disruptor",
    "Drow Ranger",
    "Enchantress",
    "Enigma",
    "Gyrocopter",
    "Huskar",
    "Invoker",
    "Jakiro",
    "Keeper of the Light",
    "Leshrac",
    "Lich",
    "Lina",
    "Lion",
    "Luna",
    "Mirana",
    "Morphling",
    "Nature's Prophet",
    "Necrolyte",
    "Outworld Destroyer",
    "Puck",
    "Pugna",
    "Queen of Pain",
    "Razor",
    "Rubick",
    "Shadow Demon",
    "Shadow Fiend",
    "Shadow Shaman",
    "Silencer",
    "Sniper",
    "Storm Spirit",
    "Tinker",
    "Vengeful Spirit",
    "Venomancer",
    "Viper",
    "Visage",
    "Warlock",
    "Weaver",
    "Windrunner",
    "Wisp",
    "Witch Doctor",
    "Zeus",
    ]

